[package]
name = "musheen-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blake3.workspace = true
fast_image_resize.workspace = true
freedesktop.workspace = true
image.workspace = true
md-5.workspace = true
musheen-core = { path = "../musheen-core" }
musheen-ops = { path = "../musheen-ops" }
open.workspace = true
png.workspace = true
posix-acl.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tree_magic_mini.workspace = true
walkdir.workspace = true
wax.workspace = true
xattr.workspace = true
xdg-mime.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
