[package]
name = "musheen-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
freedesktop.workspace = true
musheen-core = { path = "../musheen-core" }
musheen-ops = { path = "../musheen-ops" }
open.workspace = true
wax.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
