listen=YES
listen_ipv6=NO
listen_address=0.0.0.0
listen_port=2990
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
chroot_local_user=YES
allow_writeable_chroot=YES
pasv_enable=YES
pasv_address=127.0.0.1
pasv_min_port=30100
pasv_max_port=30109
seccomp_sandbox=NO
ssl_enable=YES
implicit_ssl=NO
force_local_logins_ssl=YES
force_local_data_ssl=YES
require_ssl_reuse=NO
ssl_tlsv1=YES
rsa_cert_file=/etc/ssl/certs/musheen-remote-ci.crt
rsa_private_key_file=/etc/ssl/private/musheen-remote-ci.key
