[package]
name = "musheen-local"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-channel.workspace = true
blake3.workspace = true
futures-lite.workspace = true
musheen-core = { path = "../musheen-core" }
musheen-ops = { path = "../musheen-ops" }
nix.workspace = true
notify.workspace = true
posix-acl.workspace = true
proc-mounts.workspace = true
reflink-copy.workspace = true
rustix.workspace = true
trash.workspace = true
walkdir.workspace = true
xattr.workspace = true

[lints]
workspace = true

[dev-dependencies]
musheen-test-support = { path = "../musheen-test-support" }
tempfile.workspace = true
